Import("dev_env")
src = [
    'exception_entry.S',
    'exception_isr.c',
    'sleep_asm.S',
    'delay_asm.S',
    'uart_param.c',
    'cpu.c',
    'platform.c',
    'io_config.c',
]
inc = [
    '.',
]

src_files = File(dev_env.subst(src))
inc_dirs = Dir(inc)
dev_env['LINKSCRIPT'] = File(dev_env.subst("link_script.txt"))
Return("src_files","inc_dirs")