
Import('app_build','image_build','env')
src = [
    'core_list_join.c',
    'core_main.c',
    'core_matrix.c',
    'core_portme.c',
    'core_state.c',
    'core_util.c',
]
inc = [
    '.'
]

if not 'mdk' in env['TOOLS']:
    app_env,app_target = app_build('coremark',src,inc,ble=False) #run in flash
    #app_env,app_target = image_build('coremark',src,inc,env.subst('$IC/ram_link.txt')) #run in ram