Import('app_build','env')
SConscript(dirs = 'uart_polling',exports=['app_build'])
SConscript(dirs = 'uart_it',exports=['app_build'])
if env['IC'] == 'le501x':
    SConscript(dirs = 'uart_dma',exports=['app_build'])