Import('app_build','image_build','env')
SConscript(dirs = 'flash_prog',exports=['image_build','env'])
SConscript(dirs = 'coremark',exports=['app_build','image_build','env'])
SConscript(dirs = 'ram_test',exports=['image_build','env'])