Import("dev_env")
src = [
    'cpu.c',
    'platform.c',
    'stack_var.c',
    'compiler/$COMPILER/startup.s',
    'compiler/$COMPILER/sleep_asm.s',
    'compiler/$COMPILER/svcall_asm.s',
    'compiler/$COMPILER/delay_asm.s',
    'integration/lsqspi_param.c',
    'integration/uart_param.c',
    'integration/modem_rf_le501x.c',
    'integration/calc_acc.c',
    'integration/lscache_param.c',
    'sleep.c',
]
inc = [
    '.',
    'integration',
]
src_files = File(dev_env.subst(src))
inc_dirs = Dir(inc)
dev_env['LINKSCRIPT'] = File(dev_env.subst("compiler/$COMPILER/link_script.txt"))
Return("src_files","inc_dirs")