Import('env')
src = [
    'src/lsqspi.c',
    'src/spi_flash.c',
    'src/uart.c',
    'src/lscache.c',
    'src/lspdm.c',
    'src/lspdm_dma.c',
    'trng/lstrng.c',
    'ecc/lsecc.c',
    'crypt/lscrypt.c',
    'iwdt/lsiwdt.c',
    'adc/lsadc.c',
    'timer/lstimer.c',
    'rtc/rtc.c',
    'spi/lsspi.c',
    'spi/lsi2s.c',
]

if env['IC'] != 'taurus':
    src += ['src/calc_div.c',
            'src/uart_dma.c',
            'src/dmac.c',
    ]

inc = [
    'trng',
    'ecc',
    'crypt',
    'iwdt',
    'adc',
    'timer',
    'rtc',
    'spi',
    'api',
    'inc',
]
src_files = File(src)
inc_dirs = Dir(inc)

Return("src_files","inc_dirs")