pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                powershell label: '', script: '''
                    scons
                '''    
            }
        }
        stage('Test') {
            steps {
                powershell label: '', script: '''

                '''
            }
        }
        stage('MDK_Build'){
            steps {
                powershell label: '', script: '''
                    scons toolchain=mdk operation=build
                '''    
            }
        }
        stage('MDK_Test') {
            steps {
                powershell label: '', script: '''

                '''
            }
        }
    }
    post {
        unsuccessful  {
            emailext body: '$DEFAULT_CONTENT' , subject: '$DEFAULT_SUBJECT' , to: 'jwzhang,mingzhou,xtzhang,weiyu,xwcai,lhyan,zxguo'
        }
    }
}