pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh label: '', script: '''
  
                '''    
            }
        }
        stage('Test') {
            options {
                timeout(time: 10, unit: 'MINUTES') 
            }
            steps {
                sh label: '', script: '''

                '''
            }
        }
    }
    post {
        unsuccessful  {
/*            emailext body: '$DEFAULT_CONTENT' , subject: '$DEFAULT_SUBJECT' , to: 'xtzhang@linkedsemi.com' */
        }
    }
}